enum Gender {
    MALE
    FEMALE
}

type Term {
    id: ID!
    title: String!
    domain: String!
    declension: Int!
    gender: Gender!
    languageCode: String!
    translations: [Translation!]
    missingLanguageCodes: [String!]
    addedBy: UserResult
}

type Translation {
    languageCode: String!
    terms: [String!]
}

type TermNotFound {
    message: String!
}

union TermResult = Term | TermNotFound

extend type Query {
    getTerm(termId: ID!): TermResult!
    getTerms(organisationId: ID!, domain: String, translated: Boolean): [TermResult!]!
}

extend type Mutation {
    createNewTerm(organisationId: ID!, title: String!, domain: String!, gender: Gender!, declension: Int!): TermResult!
    addTranslations(termId: ID!, translations: [String!]!, languageCode: String!): TermResult!
    removeTranslations(termId: ID!, languageCode: String): TermResult!
}
